# Generated by Django 4.1.4 on 2022-12-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authro',
            new_name='author',
        ),
    ]
