# Generated by Django 4.1.4 on 2022-12-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_authro_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
