# Generated by Django 4.1.4 on 2022-12-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
